version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=billing
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - /var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:3.7.5-management'
    hostname: app-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      - RABBITMQ_ERLANG_COOKIE=6085e2412b6fa88647466c6a81c0cea0
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
      - RABBITMQ_DEFAULT_VHOST=/